// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using transportadores.infra;

#nullable disable

namespace transportadores.infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250329214709_aaaa")]
    partial class aaaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("transportadores.dominio.entidades.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataProximaManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("QuilometragemProximaManutencao")
                        .HasColumnType("real");

                    b.Property<float>("QuilometragemUltimaManutencao")
                        .HasColumnType("real");

                    b.Property<int>("TipoPecaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaManutenção")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoPecaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Peca");
                });

            modelBuilder.Entity("transportadores.dominio.entidades.TipoPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KilometragemRevisao")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoPeca");
                });

            modelBuilder.Entity("transportadores.dominio.entidades.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Quilometragem")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("transportadores.dominio.entidades.Peca", b =>
                {
                    b.HasOne("transportadores.dominio.entidades.TipoPeca", "TipoPeca")
                        .WithMany("PecasRegistradas")
                        .HasForeignKey("TipoPecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("transportadores.dominio.entidades.Veiculo", "Veiculo")
                        .WithMany("Pecas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPeca");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("transportadores.dominio.entidades.TipoPeca", b =>
                {
                    b.Navigation("PecasRegistradas");
                });

            modelBuilder.Entity("transportadores.dominio.entidades.Veiculo", b =>
                {
                    b.Navigation("Pecas");
                });
#pragma warning restore 612, 618
        }
    }
}
